include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    one_member_abstracts: ignore # Disabled due to this demo simplicity

linter:
  rules:
    public_member_api_docs: false